server:
  port: 8888

oss:
  accessId: LTAI4GJfwJS9RW52fCCGLxuP           #ÇëÌîĞ´ÄúµÄAccessKeyId¡£
  accessKey: UNBmVesTbcLAnyexMX4FNMProlZsXl    #ÇëÌîĞ´ÄúµÄAccessKeySecret¡£
  endpoint: oss-cn-beijing.aliyuncs.com        #ÇëÌîĞ´ÄúµÄ endpoint¡£
  bucket: aliyunoss-test                       #ÇëÌîĞ´ÄúµÄ bucketname ¡£

