server:
  port: 8888

oss:
  accessId: ******************           #ÇëÌîĞ´ÄúµÄAccessKeyId¡£
  accessKey: ******************     #ÇëÌîĞ´ÄúµÄAccessKeySecret¡£
  endpoint: ******************         #ÇëÌîĞ´ÄúµÄ endpoint¡£
  bucket: ******************                       #ÇëÌîĞ´ÄúµÄ bucketname ¡£

